#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication surfaceFeatureExtract

runApplication blockMesh

runApplication snappyHexMesh -overwrite
runApplication transformPoints -scale "(0.001 0.001 0.001)"

runApplication decomposePar

runParallel $(getApplication)

runApplication reconstructPar -latestTime

#------------------------------------------------------------------------------
